// src/reporter/markdownReporter.ts
// Builds a structured Markdown impact report from an AnalysisResult.

import type { AnalysisResult, ChangedFile, FileCategory, RiskLevel } from "../types.js";
import { categoryLabel } from "../analyzer/fileClassifier.js";

function riskEmoji(level: RiskLevel): string {
  const map: Record<RiskLevel, string> = {
    low: "🟢",
    medium: "🟡",
    high: "🟠",
    critical: "🔴",
  };
  return map[level];
}

function formatFile(file: ChangedFile): string {
  const badges: string[] = [];
  if (file.isNew) badges.push("NEW");
  if (file.isDeleted) badges.push("DELETED");
  if (file.isRenamed) badges.push(`RENAMED from \`${file.oldPath}\``);

  const stats = `+${file.additions}/-${file.deletions}`;
  const badgeStr = badges.length > 0 ? ` _(${badges.join(", ")})_` : "";
  return `- \`${file.path}\` \`${stats}\`${badgeStr}`;
}

function groupFilesByCategory(
  files: ChangedFile[]
): Map<FileCategory, ChangedFile[]> {
  const map = new Map<FileCategory, ChangedFile[]>();
  for (const file of files) {
    const list = map.get(file.category) ?? [];
    list.push(file);
    map.set(file.category, list);
  }
  return map;
}

export function buildMarkdownReport(result: AnalysisResult): string {
  const { meta, changedFiles, relatedTests, missingTestWarnings, risk, verificationChecklist, downstreamImpact, configWarnings } = result;

  const totalAdditions = changedFiles.reduce((s, f) => s + f.additions, 0);
  const totalDeletions = changedFiles.reduce((s, f) => s + f.deletions, 0);
  const riskIcon = riskEmoji(risk.level);

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────
  lines.push(`# PatchLens Impact Report`);
  lines.push("");
  lines.push(`> Generated by [PatchLens](https://github.com/YOUR_USERNAME/patchlens) on ${new Date(meta.analyzedAt).toLocaleString()}`);
  lines.push("");

  // ── Summary ─────────────────────────────────────────────────
  lines.push(`## Summary`);
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| Base | \`${meta.base}\` |`);
  lines.push(`| Head | \`${meta.head}\` |`);
  lines.push(`| Repository | \`${meta.repoPath}\` |`);
  lines.push(`| Files Changed | ${changedFiles.length} |`);
  lines.push(`| Lines Added | +${totalAdditions} |`);
  lines.push(`| Lines Deleted | -${totalDeletions} |`);
  lines.push(`| Risk Level | ${riskIcon} **${risk.level.toUpperCase()}** (score: ${risk.score}/100) |`);
  lines.push("");
  lines.push(`**${risk.explanation}**`);
  lines.push("");

  // ── Risk Score Breakdown ─────────────────────────────────────
  lines.push(`## ${riskIcon} Risk Score Breakdown`);
  lines.push("");
  if (risk.factors.length === 0) {
    lines.push("No significant risk factors detected.");
  } else {
    lines.push("| Factor | Weight |");
    lines.push("|--------|--------|");
    for (const factor of risk.factors) {
      lines.push(`| ${factor.description} | ${factor.weight}/100 |`);
    }
  }
  lines.push("");

  // ── Changed Files by Category ────────────────────────────────
  lines.push(`## Changed Files`);
  lines.push("");

  const grouped = groupFilesByCategory(changedFiles);
  const categoryOrder: FileCategory[] = [
    "dependency", "config", "schema", "routes", "source", "ui", "test", "docs", "unknown"
  ];

  for (const cat of categoryOrder) {
    const files = grouped.get(cat);
    if (!files || files.length === 0) continue;

    lines.push(`### ${categoryLabel(cat)} (${files.length})`);
    lines.push("");
    for (const file of files) {
      lines.push(formatFile(file));
    }
    lines.push("");
  }

  // ── Directly Affected Areas ──────────────────────────────────
  lines.push(`## Directly Affected Areas`);
  lines.push("");
  for (const area of result.affectedAreas) {
    lines.push(`- \`${area}/\``);
  }
  lines.push("");

  // ── Downstream Impact ────────────────────────────────────────
  lines.push(`## Possible Downstream Impact`);
  lines.push("");
  for (const impact of downstreamImpact) {
    lines.push(`- ${impact}`);
  }
  lines.push("");

  // ── Related Tests ────────────────────────────────────────────
  lines.push(`## Related Tests`);
  lines.push("");
  if (relatedTests.length === 0) {
    lines.push("No related test files found in this diff.");
  } else {
    for (const t of relatedTests) {
      lines.push(`- \`${t.testFile}\` → covers \`${t.sourceFile}\` _(${t.reason})_`);
    }
  }
  lines.push("");

  // ── Missing Test Warnings ────────────────────────────────────
  lines.push(`## ⚠️ Missing Test Warnings`);
  lines.push("");
  if (missingTestWarnings.length === 0) {
    lines.push("✅ All changed source files appear to have corresponding tests in this diff.");
  } else {
    for (const w of missingTestWarnings) {
      lines.push(`- ⚠️ \`${w.sourceFile}\` — ${w.reason}`);
    }
  }
  lines.push("");

  // ── Config and Dependency Warnings ──────────────────────────
  if (configWarnings.length > 0) {
    lines.push(`## ⚙️ Config & Dependency Warnings`);
    lines.push("");
    for (const w of configWarnings) {
      lines.push(`- ${w}`);
    }
    lines.push("");
  }

  // ── Verification Checklist ───────────────────────────────────
  lines.push(`## ✅ Suggested Verification Checklist`);
  lines.push("");
  const areaGroups = new Map<string, typeof verificationChecklist>();
  for (const item of verificationChecklist) {
    const group = areaGroups.get(item.area) ?? [];
    group.push(item);
    areaGroups.set(item.area, group);
  }

  for (const [area, items] of areaGroups) {
    lines.push(`**${area}**`);
    for (const item of items) {
      lines.push(`- [ ] ${item.action}`);
    }
    lines.push("");
  }

  // ── Footer ───────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push(`_Report generated by PatchLens v0.1.0 — [https://github.com/YOUR_USERNAME/patchlens](https://github.com/YOUR_USERNAME/patchlens)_`);

  return lines.join("\n");
}